### ISSUE TITLE
Files for jsPanel 4.10.0 Look Like v4.9.5 Files?

### ISSUE THREAD

**Issue by geoffblandrbs** [Flyer53/jsPanel4#122]
The latest 4.10.0 release jsPanel.css and jsPanel.js files still have version numbers of 4.9.5 in the comments at the top. 

Checking the actual contents of the jsPanel.js for v4.10.0 I don;t see any changes and change log leads me to expect some. 

Is 4.10.0 downloading the correct files?

**Comment by Flyer53** [comment]
Using the &lt;Clone or Download&gt; button on GitHub downloads the wrong files indeed. Corrected that already.

All the rest is fine. It's just the comments that did not update for some reason. I probably had `package.json` still on v4.9.5 when I run the build. The files itself are 4.10.0. You can check that with the prop `jsPanel.version`.

Sorry for the inconvenience

**Comment by Flyer53** [comment]
I pushed new files. So downloading via the &lt;Clone or Download&gt; button downloads files with correct version AND comments.

**Comment by geoffblandrbs** [comment]
Thanks for teh prompt fix Stefan. 

I wasn't using Github, I was using the download button from your website that links to https://jspanel.de/downloads/jspanel-4.10.0.zip

I can see that the version stamped in the js code is now "4.10.0'.

But there;s a comment at the top of both the js and css file that still shows version 4.9.5 which may confuse users.

` * @version v4.9.5`

**Comment by Flyer53** [comment]
Hi Geoff,
You're right ... it was just the version reference in _package.json_ I forgot to update leading to the wrong comment. Fixed that as well. Thanks for the hint.

Stay healthy,
Stefan

**Comment by geoffblandrbs** [comment]
I just downloaded from your website from the "Download latest stable" version. The .js and .css files still have comments at the top stating they are version 4.9.5.

**Comment by Flyer53** [comment]
Mmmmh, weird ...
Just downloaded it myself from jspanel.de and everything is fine.

**Comment by geoffblandrbs** [comment]
Very weird, I just downloaded again (11:30) and still have the following comments at the top of the  files. 

dist\jspanel.js

```
/**
 * jsPanel - A JavaScript library to create highly configurable multifunctional floating panels that can also be used as modal, tooltip, hint or contextmenu
 * @version v4.9.5
 * @homepage https://jspanel.de/
 * @license MIT
 * @author Stefan Sträßer - info@jspanel.de
 * @github https://github.com/Flyer53/jsPanel4.git
 */
```

dist\jspanel.css

```
/**
 * jsPanel - A JavaScript library to create highly configurable multifunctional floating panels that can also be used as modal, tooltip, hint or contextmenu
 * @version v4.9.5
 * @homepage https://jspanel.de/
 * @license MIT
 * @author Stefan Sträßer - info@jspanel.de
 * @github https://github.com/Flyer53/jsPanel4.git
 */
```

**Comment by Flyer53** [comment]
I don't understand it. To verify once again I fetched the zip via FTP and everything is fine.
Is it possible that the copy you get is cached somewhere? So that you don't get the updated one?

Whatever it is ... the actual js is the current v4.10.0.

**Comment by geoffblandrbs** [comment]
Sorry - you are correct it is some kind of caching issue on our side.
I was able to download it at home and all versions in the comments were correct. 
This is fixed now. Thanks.
